language: cpp
dist: trusty

sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-5.0

    packages:
    - cmake
    - catch
    - g++-7
    - clang-5.0

matrix:
  include:
    - env: COMPILER=g++-7
    - env: COMPILER=clang++-5.0

script:
  - mkdir build
  - cd build
  - export CXX=$COMPILER
  - cmake ..
  - make
  - ctest
