language: cpp
dist: trusty

sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise
    packages:
    - cmake
    - catch
    - g++-7
    - clang-5.0
    
matrix:
  include:
    - compiler: gcc
      env: COMPILER=g++-7
            
    - compiler: clang
      env: COMPILER=clang++-5.0
        

#before_install:
  # C++14
 # - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 # - sudo apt update -qq

#install: 
  # C++14
#  - sudo apt install -qq g++-7 cmake catch
#  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  
script:
  - mkdir build
  - cd build
  - echo $compiler
  - echo $COMPILER
  - export CXX=$COMPILER
  - cmake ..
  - make
  - ./tests/const_string_test
